--- pyproject.toml.orig	2025-09-11 02:36:48 UTC
+++ pyproject.toml
@@ -38,7 +38,7 @@ requires = [
     # redistributors can do this by installing the numpy version they like and
     # disabling build isolation.
     # NOTE: need numpy>=2.1.3 for free-threaded CPython support
-    "numpy>=2.0.0,<2.6",
+    "numpy>=1.26.4,<2.6",
 ]
 
 [project]
